bashrc2: move some old functions into scripts

diff --git a/test/keep/bashrc2 b/test/keep/bashrc2
--- a/test/keep/bashrc2
+++ b/test/keep/bashrc2
@@ -57,48 +57,6 @@ NC='\e[0m'              # No Color
 # --> Nice. Has the same effect as using "ansi.sys" in DOS.
 
 
-function initial_setup_copy()
-{
-  # copy all files in folder to ~
-  local folder=$1
-  local dest=${HOME}
-  [ -n "$2" ] && dest="$2"
-  if [ -z "${folder}" -o  ! -d "${folder}" ]; then
-    echo "need to provide a folder with files to copy"
-    return 1
-  fi
-  if [ -z "${dest}" -o  ! -d "${dest}" ]; then
-    echo "target $dest doesn't exist or not a folder"
-    return 1
-  fi
-  echo "input=$folder destination=$dest"
-  local target
-  local from
-  local exists
-  for fn in $(command ls -A $folder); do
-    from="${folder}/${fn}"
-    target="${dest}/${fn}"
-    exists="="
-    echo "processing $from"
-    if [ -d "${from}" ]; then
-      # can bash handle recursive?
-      mkdir -p $target >& /dev/null
-      initial_setup_copy "${from}" "${target}"
-      exists="_"
-    else
-      if [ -e  "${target}" ]; then
-        # it's a file and already exists
-        exists="#"
-      else
-        cp -i "${from}" "${target}"
-      fi
-    fi
-    if [ "${exists}" != "_" ]; then
-      printf "%s %-40s => %s\n" $exists $from $target
-    fi
-  done
-}
-
 function py() {
   # should we go with python by default or python 3?
   type python3 >& /dev/null && PYTHON_EXE=python3 || PYTHON_EXE=python
@@ -193,15 +151,6 @@ function powerprompt()
 #
 #===============================================================
 
-#-------------------
-# Personnal Aliases
-#-------------------
-
-#alias rm='rm -i'
-#alias cp='cp -i'
-#alias mv='mv -i'
-# -> Prevents accidentally clobbering files.
-
 export PAGER=less
 #export LESSCHARSET='latin1'
 #export LESSOPEN='|/usr/bin/lesspipe.sh %s 2>& /dev/null' # Use this if lesspipe.sh exists
@@ -223,8 +172,6 @@ function xtitle ()
   echo -n -e "\033]0;$*\007"
 }
 
-
-#function ll(){ ls -l "$@"| egrep "^d" ; ls -lXB "$@" 2>&-| egrep -v "^d|total "; }
 function ll() {
   if type eza >& /dev/null; then
     eza -l --git --icons "$@"
@@ -232,7 +179,6 @@ function ll() {
     ls -l "$@"| egrep "^d" ; ls -lXB "$@" 2>&-| egrep -v "^d|total "
   fi
 }
-
 
 #-----------------------------------
 # File & strings related functions:
@@ -326,7 +272,6 @@ function ddo() #try to do something with every file passed on the command line
   done
 }
 
-
 function path ( )
 {
   if test -z "$1"; then
@@ -375,19 +320,18 @@ function gtp()
   PS1="[\h] \W $(__git_ps1) > "
 }
 
-if true; then
-  # try new implementation for d
-  __d_add_folder()
-  {
-    local name_orig=$1
-    [ -z "${name_orig}" ] && echo "__d_add_folder: cannot add. Nothing provided." && return 1
-    #[ ! -d "${name}" ] && echo "cannot add. Folder ${name} missing." && return 1
+## d imp {{{
+__d_add_folder()
+{
+  local name_orig=$1
+  [ -z "${name_orig}" ] && echo "__d_add_folder: cannot add. Nothing provided." && return 1
+  #[ ! -d "${name}" ] && echo "cannot add. Folder ${name} missing." && return 1
 
-    if ! name=$(eval "cd $name_orig" >& /dev/null && readlink -e . ); then
-      echo "__d_add_folder: $name_orig not found. Cannot add"
-      return 1
-    fi
-    local key=$2
+  if ! name=$(eval "cd $name_orig" >& /dev/null && readlink -e . ); then
+    echo "__d_add_folder: $name_orig not found. Cannot add"
+    return 1
+  fi
+  local key=$2
 
   # use a vector where is element is another vector
   local size=${#_dirs_data_keys[@]}
@@ -493,223 +437,7 @@ dn()
   echo name=$name
   cd "$name"
 }
-
-elif test ${BASH_VERSION:0:1} -ge 4 ; then
-  if test -z "${_my_dirs_data}" ; then declare -A _my_dirs_data; fi
-
-  function d()
-  {
-    # get current folders in _my_dirs_data and dirs -v
-    # will list each key followed by dirs
-    local key
-    local dkey
-    local -A ff_tag
-    local -A ff_dirs
-    local -a mdirs
-    local one_dir_key
-
-    for key in "${!_my_dirs_data[@]}" ; do
-      dkey="${_my_dirs_data[${key}]}"
-      if test -z "${ff_tag[${dkey}]}";  then
-        ff_tag[${dkey}]="${key}"
-      else
-        ff_tag[${dkey}]="${ff_tag[${dkey}]}:${key}"
-      fi
-    done
-
-    mdirs=($(dirs -l -p))
-    local idx=-1
-    for dkey in "${mdirs[@]}"; do
-      let idx++
-      if test $idx -eq 0; then continue; fi
-      if test -z "${ff_dirs[${dkey}]}";  then
-        ff_dirs[${dkey}]="${idx}"
-      else
-        ff_dirs[${dkey}]="${ff_dirs[${dkey}]}:${idx}"
-      fi
-    done
-
-    if test $# -eq 0; then
-      for key in "${!ff_tag[@]}"; do
-        one_dir_key=${ff_dirs[${key}]}
-        one_dir_key=(${one_dir_key//:/ })
-        one_dir_key=${one_dir_key[0]}
-        printf "%-10s %2s %-s\n" "${ff_tag[${key}]}" "${one_dir_key}" "${key/${HOME}/~}"
-      done
-      for key in "${!ff_dirs[@]}"; do
-        if test -n "${ff_tag[${key}]}"; then continue; fi
-        one_dir_key=${ff_dirs[${key}]}
-        one_dir_key=(${one_dir_key//:/ })
-        one_dir_key=${one_dir_key[0]}
-        printf "%-10s %2s %-s\n" " " "${one_dir_key}" "${key/${HOME}/~}"
-      done
-      return
-    fi
-
-    local curdir=${PWD}
-
-    if test "$1" = "-"; then
-      command cd -
-      return
-    fi
-
-    local -a tmp_arr
-
-    if test "$1" = "--"; then
-      local deldir
-      if test -z "$2"; then
-        deldir="${curdir}"
-      elif test -n "${_my_dirs_data[${2}]}"; then
-        deldir="${_my_dirs_data[${2}]}"
-      elif test "$2" -ge 0 >& /dev/null; then
-        deldir=$(eval "dirs -l +${2}")
-      else
-        deldir=$(realpath "$2")
-      fi
-      if test -n "${ff_tag[${deldir}]}"; then
-        IFS=':' read -a tmp_arr <<< ${ff_tag[${deldir}]}
-        tmp_arr=(${tmp_arr})
-        for i in "${tmp_arr[@]}"; do
-          unset _my_dirs_data[${i}]
-        done
-      fi
-
-      if test -n "${ff_dirs[${deldir}]}"; then
-        IFS=':' read -a tmp_arr <<< ${ff_dirs[${deldir}]}
-        tmp_arr=(${tmp_arr})
-        for((i=${#tmp_arr[@]}-1; i>=0; i--)); do
-          eval "popd -n +${tmp_arr[$i]}" > /dev/null
-        done
-      fi
-      return
-    fi
-
-    if test "$1" = "+"; then
-      # add folder to dirs even it exists already
-      if test -n "$2"; then
-        pushd "$2" > /dev/null
-        pushd -n +1
-      else
-        pushd "${curdir}" > /dev/null
-        pushd -n +1
-      fi
-      return
-    fi
-
-    if test "${1:0:1}" = "+"; then
-      # add tag (bookmark)
-      local tag
-      tag="${1:1}"
-      if test -n "$2"; then
-        pushd "$2" > /dev/null
-        pushd -n +1
-      else
-        pushd "${PWD}" > /dev/null
-        pushd -n +1
-      fi
-      _my_dirs_data[${tag}]=$(realpath "${PWD}")
-      return
-    fi
-
-    # when to add info to the correct hash array
-    # finally cd to the current folder
-    if test -n "${_my_dirs_data[${1}]}"; then
-      eval "cd ${_my_dirs_data[${1}]}"
-      __save_folder_hist "$PWD"
-    elif test "$1" -ge 0 >& /dev/null; then
-      eval "cd $(dirs +$1)"
-      __save_folder_hist "$PWD"
-    else
-      cd $1
-      __save_folder_hist "$PWD"
-    fi
-    return
-  }
-
-  __list_folder_hist()
-  {
-    # first argument is folder to be kept in history.
-    # history will not be deleted so don't need much manipulation
-    let i=0
-    for key in "${__my_dirs_history[@]}"; do
-      printf "%-30s   --  %s\n" "${key/${HOME}/~}" "$i"
-      let i+=1
-    done
-  }
-  __save_folder_hist()
-  {
-    local cand=$1
-    for key in "${__my_dirs_history[@]}"; do
-      if test "${cand}" = "${key}"; then
-        return
-      fi
-    done
-    # got here just add it to end of list
-    __my_dirs_history+=("${cand}")
-  }
-  __change_folder_hist()
-  {
-    # change to a folder in history specifying a key
-    # we assume the key will be valid
-    if test "$1" -ge "${#__my_dirs_history[@]}" >& /dev/null; then
-      return
-    fi
-    d "${__my_dirs_history[$1]}"
-  }
-  #interface function
-  dh() {
-    if test "a$1" = "a"; then
-      __list_folder_hist
-    else
-      __change_folder_hist "$1"
-    fi
-  }
-
-  function _d()
-  {
-    local cur=${COMP_WORDS[COMP_CWORD]}
-    COMPREPLY=( $(eval "compgen -W \"${!_my_dirs_data[@]}\" -- $cur") )
-  }
-  complete -o plusdirs -o nospace -F _d d
-
-  function __d_add_folder()
-  {
-    #echo --1=$1-- --2=$2--
-    # usage: $0 destination tag
-    if test "a$1" = "a"; then return; fi
-    # check if key already added, to many for push/popd
-    existing=0
-    for key in ${_my_dirs_data[@]}; do
-      if test "$key" = "$1"; then
-        existing=1;
-        break;
-      fi
-    done
-    if test "$existing" = "0"; then
-      pushd -n "$1" > /dev/null
-    fi
-    if test "a$2" = "a"; then return; fi
-    _my_dirs_data["$2"]="$1"
-  }
-else
-  function d()
-  {
-    if test $# -eq 0; then
-      dirs -v
-    else
-      if test $1 -ge 1 -o $1 -le 20 >& /dev/null; then
-        eval "cd ~$1"
-      else
-        if test "$1" = "-"; then
-          cd -
-        else
-          pushd $1 >& /dev/null
-          if test $? -ne 0; then pushd $1 ; fi
-        fi
-      fi
-    fi
-  }
-fi
+## d imp }}}
 
 function tt()
 {
